services:
  mongodb:
    profiles:
      - "backing-service"
      - "all"
      - "dev"
      - "api"
    image: mongo:latest
    container_name: natours_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "example"
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017

  mongo-express:
    profiles:
      - "backing-service"
      - "all"
      - "dev"
      - "api"
    image: mongo-express:latest
    container_name: natours_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "example"
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
    depends_on:
      mongodb:
        condition: service_started

  redis:
    profiles:
      - "backing-service"
      - "all"
      - "dev"
      - "api"
    container_name: natours_redis
    image: redis:latest
    restart: always
    volumes:
      - 'redis_vol:/data'
    ports:
      - '6379:6379'
    env_file:
      - ./apps/api/docker.env


  api-dev:
    profiles:
      - "dev"
      - "api"
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: installer
    container_name: natours-development-api
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/api/node_modules
      # - /app/packages/utils/node_modules
    environment:
      MONGODB_URL: mongodb://root:example@mongodb:27017/natours-nest-next?authSource=admin
      PORT: 8080
      NODE_ENV: development
    ports:
      - "8080:8080"
      - "9229:9229" # For debugging
    depends_on:
      mongodb:
        condition: service_started
      redis:
        condition: service_started
    env_file:
      - ./apps/api/docker.env
    command: >
      sh -c "cd /app && rm -rf .env && pnpm --filter=api seed:db && pnpm --filter=api dev"

  api:
    profiles:
      - "all"
      - "api"
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: packager
    container_name: natours-production-api
    environment:
      MONGODB_URL: mongodb://root:example@mongodb:27017/natours-nest-next?authSource=admin
      NODE_ENV: production
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      # migrate:
      #   condition: service_completed_successfully
      mongodb:
        condition: service_started
      redis:
        condition: service_started
    env_file:
      - ./apps/api/docker.env


  web:
    profiles:
      - all
    build:
      context: .
      dockerfile: ./web/Dockerfile
      args:
        NODE_ENV: development
    image: natours-client:latest
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - server
    environment:
      - PUBLIC_URL=http://localhost:4000
      - PUBLIC_SERVER_URL=http://localhost:4100

volumes:
  redis_vol:
    driver: local
  mongodb_data:
