services:
  mongodb:
    profiles:
      - all
      - backing_service
    image: mongo:latest
    container_name: natours_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "example"
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017

  mongo-express:
    profiles:
      - all
      - backing_service
    image: mongo-express:latest
    container_name: natours_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "example"
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
    depends_on:
      - mongodb

  redis:
    profiles:
      - all
      - backing_service
    image: redis:6.2-alpine
    restart: always
    container_name: natours_redis
    volumes:
      - 'redis_vol:/data'
    ports:
      - '6379:6379'
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_PASSWORD=redis_password
    command: redis-server --save 20 1 --loglevel warning --requirepass redis_password

  client:
    profiles:
      - all
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        NODE_ENV: development
    image: natours-client:latest
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - server
    environment:
      - PUBLIC_URL=http://localhost:4000
      - PUBLIC_SERVER_URL=http://localhost:4100

  server:
    profiles:
      - all
      - server
    image: node:22-alpine
    working_dir: /app
    container_name: natours_server
    volumes:
      - ./server:/app
      - /app/node_modules # prevents overriding node modules inside the container
    ports:
      - 4100:4100
    depends_on:
      - mongodb
      - redis
    env_file:
      - ./server/.env
    environment:
      MONGODB_URL: mongodb://root:example@mongodb:27017/natours-nest-next?authSource=admin
      NODE_ENV: development
    command: >
      sh -c "npm install -g pnpm &&
            pnpm install &&
            pnpm rebuild sharp &&
            pnpm nest start --watch
      "
    links:
      - mongodb
      - redis

volumes:
  redis_vol:
    driver: local
  mongodb_data:
