/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Bloomers Commerce
 * From parents, for parents
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customInstance } from './axios';
export interface SignupDto {
  [key: string]: unknown;
}

export interface CustomerEntity {
  id: string;
  userId: string;
  /** @nullable */
  fullName: string | null;
}

export interface StoreOwnerProfileEntity {
  id: string;
  userId: string;
  /** @nullable */
  fullName: string | null;
}

export interface AdminProfileEntity {
  id: string;
  userId: string;
  /** @nullable */
  fullName: string | null;
}

export interface UserProfileEntity {
  id: string;
  userId: string;
  /** @nullable */
  fullName: string | null;
}

/**
 * @nullable
 */
export type UserEntityCustomer = CustomerEntity | null;

/**
 * @nullable
 */
export type UserEntityStoreOwnerProfile = StoreOwnerProfileEntity | null;

/**
 * @nullable
 */
export type UserEntityAdminProfile = AdminProfileEntity | null;

export type UserEntityRole = { [key: string]: unknown };

export interface UserEntity {
  /** @nullable */
  customer?: UserEntityCustomer;
  /** @nullable */
  storeOwnerProfile?: UserEntityStoreOwnerProfile;
  /** @nullable */
  adminProfile?: UserEntityAdminProfile;
  /** */
  profile: UserProfileEntity;
  id: string;
  email: string;
  isImpersonated?: boolean;
  impersonatedBy?: string;
  role: UserEntityRole;
}

export interface LoginDto {
  email: string;
  /** @minLength 6 */
  password: string;
}

export interface ValidationErrorEntity {
  message: string[];
  error: string;
  statusCode: number;
}

export interface ResponseErrorEntity {
  message: string;
  error: string;
  statusCode: number;
}

export interface ImpersonateUserDto {
  impersonateUserId: string;
}

export interface StopImpersonationDto {
  [key: string]: unknown;
}

export interface ConfirmEmailDto {
  email: string;
  /** Non-hashed email confirmation token */
  token: string;
}

export interface SimpleMessageEntity {
  /** Message indicating what happened */
  message: string;
  /** Indicates if action happened successfully or not */
  success: boolean;
}

export interface ForgotPasswordDto {
  /** @maxLength 255 */
  email: string;
}

export interface ResetPasswordDto {
  token: string;
  password: string;
}

export interface ProductCategoryEntity {
  /** @nullable */
  subCategories?: ProductCategoryEntity[] | null;
  id: string;
  title: string;
  /** @nullable */
  cardImage: string | null;
  /** @nullable */
  storeId: string | null;
  /** @nullable */
  parentCategoryId: string | null;
}

export interface ProductImageEntity {
  id: string;
  storeId: string;
  productId: string;
  url: string;
}

export interface ProductReviewEntity {
  id: string;
  storeId: string;
  productId: string;
  customerId: string;
  reviewText: string;
}

export interface ProductVariantEntity {
  price: string;
  id: string;
  storeId: string;
  productId: string;
  stock: number;
  sku: string;
}

export interface ProductDisCountEntity {
  amount: string;
  /** @nullable */
  minOrderValue: string | null;
  code: string;
}

export interface ProductStoreEntity {
  name: string;
  id: string;
}

/**
 * @nullable
 */
export type ProductEntityDiscount = ProductDisCountEntity | null;

export interface ProductEntity {
  /** */
  isBloomers: boolean;
  /** */
  isDiscounted: boolean;
  basePrice: string;
  discountPrice?: string;
  /** @nullable */
  images?: ProductImageEntity[] | null;
  /** @nullable */
  reviews?: ProductReviewEntity[] | null;
  /** */
  ratings: ProductReviewEntity[];
  /** */
  variants: ProductVariantEntity[];
  /** @nullable */
  discount?: ProductEntityDiscount;
  /** */
  store?: ProductStoreEntity;
  name: string;
  id: string;
  /** @nullable */
  storeId: string | null;
  /** @nullable */
  description: string | null;
  categoryId: string;
  /** @nullable */
  subCategoryId: string | null;
  productRating: number;
  numberSold: number;
  /** @nullable */
  discountId: string | null;
}

export interface CreateActivityLogDto {
  storeId?: string;
  userId: string;
  action: string;
  ipAddress?: string;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const signup = (
  signupDto: SignupDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<UserEntity>(
    {
      url: `/api/v1/auth/signup`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: signupDto,
      signal,
    },
    options,
  );
};

export const getSignupMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signup>>,
    TError,
    { data: SignupDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signup>>,
  TError,
  { data: SignupDto },
  TContext
> => {
  const mutationKey = ['signup'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signup>>,
    { data: SignupDto }
  > = (props) => {
    const { data } = props ?? {};

    return signup(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SignupMutationResult = NonNullable<
  Awaited<ReturnType<typeof signup>>
>;
export type SignupMutationBody = SignupDto;
export type SignupMutationError = unknown;

export const useSignup = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signup>>,
    TError,
    { data: SignupDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof signup>>,
  TError,
  { data: SignupDto },
  TContext
> => {
  const mutationOptions = getSignupMutationOptions(options);

  return useMutation(mutationOptions);
};

export const login = (
  loginDto: LoginDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<UserEntity>(
    {
      url: `/api/v1/auth/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: loginDto,
      signal,
    },
    options,
  );
};

export const getLoginMutationOptions = <
  TError = ValidationErrorEntity | ResponseErrorEntity,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    { data: LoginDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: LoginDto },
  TContext
> => {
  const mutationKey = ['login'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof login>>,
    { data: LoginDto }
  > = (props) => {
    const { data } = props ?? {};

    return login(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof login>>
>;
export type LoginMutationBody = LoginDto;
export type LoginMutationError = ValidationErrorEntity | ResponseErrorEntity;

export const useLogin = <
  TError = ValidationErrorEntity | ResponseErrorEntity,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    { data: LoginDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: LoginDto },
  TContext
> => {
  const mutationOptions = getLoginMutationOptions(options);

  return useMutation(mutationOptions);
};

export const impersonateUser = (
  impersonateUserDto: ImpersonateUserDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<UserEntity>(
    {
      url: `/api/v1/auth/impersonate`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: impersonateUserDto,
      signal,
    },
    options,
  );
};

export const getImpersonateUserMutationOptions = <
  TError = ResponseErrorEntity,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof impersonateUser>>,
    TError,
    { data: ImpersonateUserDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof impersonateUser>>,
  TError,
  { data: ImpersonateUserDto },
  TContext
> => {
  const mutationKey = ['impersonateUser'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof impersonateUser>>,
    { data: ImpersonateUserDto }
  > = (props) => {
    const { data } = props ?? {};

    return impersonateUser(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ImpersonateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof impersonateUser>>
>;
export type ImpersonateUserMutationBody = ImpersonateUserDto;
export type ImpersonateUserMutationError = ResponseErrorEntity;

export const useImpersonateUser = <
  TError = ResponseErrorEntity,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof impersonateUser>>,
    TError,
    { data: ImpersonateUserDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof impersonateUser>>,
  TError,
  { data: ImpersonateUserDto },
  TContext
> => {
  const mutationOptions = getImpersonateUserMutationOptions(options);

  return useMutation(mutationOptions);
};

export const stopImpersonation = (
  stopImpersonationDto: StopImpersonationDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<UserEntity>(
    {
      url: `/api/v1/auth/stop-impersonation`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: stopImpersonationDto,
      signal,
    },
    options,
  );
};

export const getStopImpersonationMutationOptions = <
  TError = ResponseErrorEntity,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof stopImpersonation>>,
    TError,
    { data: StopImpersonationDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof stopImpersonation>>,
  TError,
  { data: StopImpersonationDto },
  TContext
> => {
  const mutationKey = ['stopImpersonation'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof stopImpersonation>>,
    { data: StopImpersonationDto }
  > = (props) => {
    const { data } = props ?? {};

    return stopImpersonation(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StopImpersonationMutationResult = NonNullable<
  Awaited<ReturnType<typeof stopImpersonation>>
>;
export type StopImpersonationMutationBody = StopImpersonationDto;
export type StopImpersonationMutationError = ResponseErrorEntity;

export const useStopImpersonation = <
  TError = ResponseErrorEntity,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof stopImpersonation>>,
    TError,
    { data: StopImpersonationDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof stopImpersonation>>,
  TError,
  { data: StopImpersonationDto },
  TContext
> => {
  const mutationOptions = getStopImpersonationMutationOptions(options);

  return useMutation(mutationOptions);
};

export const refreshToken = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<UserEntity>(
    { url: `/api/v1/auth/refresh-token`, method: 'POST', signal },
    options,
  );
};

export const getRefreshTokenMutationOptions = <
  TError = ResponseErrorEntity,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof refreshToken>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof refreshToken>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['refreshToken'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof refreshToken>>,
    void
  > = () => {
    return refreshToken(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RefreshTokenMutationResult = NonNullable<
  Awaited<ReturnType<typeof refreshToken>>
>;

export type RefreshTokenMutationError = ResponseErrorEntity;

export const useRefreshToken = <
  TError = ResponseErrorEntity,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof refreshToken>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof refreshToken>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getRefreshTokenMutationOptions(options);

  return useMutation(mutationOptions);
};

export const getProfile = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<UserEntity>(
    { url: `/api/v1/auth/profile`, method: 'GET', signal },
    options,
  );
};

export const getGetProfileQueryKey = () => {
  return [`/api/v1/auth/profile`] as const;
};

export const getGetProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof getProfile>>,
  TError = ResponseErrorEntity,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getProfile>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProfileQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProfile>>> = ({
    signal,
  }) => getProfile(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProfile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProfile>>
>;
export type GetProfileQueryError = ResponseErrorEntity;

export function useGetProfile<
  TData = Awaited<ReturnType<typeof getProfile>>,
  TError = ResponseErrorEntity,
>(options: {
  query: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getProfile>>, TError, TData>
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getProfile>>,
        TError,
        Awaited<ReturnType<typeof getProfile>>
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof customInstance>;
}): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProfile<
  TData = Awaited<ReturnType<typeof getProfile>>,
  TError = ResponseErrorEntity,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getProfile>>, TError, TData>
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getProfile>>,
        TError,
        Awaited<ReturnType<typeof getProfile>>
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProfile<
  TData = Awaited<ReturnType<typeof getProfile>>,
  TError = ResponseErrorEntity,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getProfile>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetProfile<
  TData = Awaited<ReturnType<typeof getProfile>>,
  TError = ResponseErrorEntity,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getProfile>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProfileQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getUserAbilities = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/api/v1/auth/abilities`, method: 'GET', signal },
    options,
  );
};

export const getGetUserAbilitiesQueryKey = () => {
  return [`/api/v1/auth/abilities`] as const;
};

export const getGetUserAbilitiesQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserAbilities>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getUserAbilities>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserAbilitiesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserAbilities>>
  > = ({ signal }) => getUserAbilities(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserAbilities>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserAbilitiesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserAbilities>>
>;
export type GetUserAbilitiesQueryError = unknown;

export function useGetUserAbilities<
  TData = Awaited<ReturnType<typeof getUserAbilities>>,
  TError = unknown,
>(options: {
  query: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getUserAbilities>>, TError, TData>
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getUserAbilities>>,
        TError,
        Awaited<ReturnType<typeof getUserAbilities>>
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof customInstance>;
}): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserAbilities<
  TData = Awaited<ReturnType<typeof getUserAbilities>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getUserAbilities>>, TError, TData>
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getUserAbilities>>,
        TError,
        Awaited<ReturnType<typeof getUserAbilities>>
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserAbilities<
  TData = Awaited<ReturnType<typeof getUserAbilities>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getUserAbilities>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetUserAbilities<
  TData = Awaited<ReturnType<typeof getUserAbilities>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getUserAbilities>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserAbilitiesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const logout = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/api/v1/auth/logout`, method: 'POST', signal },
    options,
  );
};

export const getLogoutMutationOptions = <
  TError = ResponseErrorEntity,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logout>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof logout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['logout'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof logout>>,
    void
  > = () => {
    return logout(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof logout>>
>;

export type LogoutMutationError = ResponseErrorEntity;

export const useLogout = <
  TError = ResponseErrorEntity,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logout>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof logout>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getLogoutMutationOptions(options);

  return useMutation(mutationOptions);
};

export const confirmAccount = (
  confirmEmailDto: ConfirmEmailDto,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<SimpleMessageEntity>(
    {
      url: `/api/v1/auth/confirm-account`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: confirmEmailDto,
    },
    options,
  );
};

export const getConfirmAccountMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof confirmAccount>>,
    TError,
    { data: ConfirmEmailDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof confirmAccount>>,
  TError,
  { data: ConfirmEmailDto },
  TContext
> => {
  const mutationKey = ['confirmAccount'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof confirmAccount>>,
    { data: ConfirmEmailDto }
  > = (props) => {
    const { data } = props ?? {};

    return confirmAccount(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ConfirmAccountMutationResult = NonNullable<
  Awaited<ReturnType<typeof confirmAccount>>
>;
export type ConfirmAccountMutationBody = ConfirmEmailDto;
export type ConfirmAccountMutationError = unknown;

export const useConfirmAccount = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof confirmAccount>>,
    TError,
    { data: ConfirmEmailDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof confirmAccount>>,
  TError,
  { data: ConfirmEmailDto },
  TContext
> => {
  const mutationOptions = getConfirmAccountMutationOptions(options);

  return useMutation(mutationOptions);
};

export const forgotPassword = (
  forgotPasswordDto: ForgotPasswordDto,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<SimpleMessageEntity>(
    {
      url: `/api/v1/auth/forgot-password`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: forgotPasswordDto,
    },
    options,
  );
};

export const getForgotPasswordMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof forgotPassword>>,
    TError,
    { data: ForgotPasswordDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof forgotPassword>>,
  TError,
  { data: ForgotPasswordDto },
  TContext
> => {
  const mutationKey = ['forgotPassword'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof forgotPassword>>,
    { data: ForgotPasswordDto }
  > = (props) => {
    const { data } = props ?? {};

    return forgotPassword(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ForgotPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof forgotPassword>>
>;
export type ForgotPasswordMutationBody = ForgotPasswordDto;
export type ForgotPasswordMutationError = unknown;

export const useForgotPassword = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof forgotPassword>>,
    TError,
    { data: ForgotPasswordDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof forgotPassword>>,
  TError,
  { data: ForgotPasswordDto },
  TContext
> => {
  const mutationOptions = getForgotPasswordMutationOptions(options);

  return useMutation(mutationOptions);
};

export const resetPassword = (
  resetPasswordDto: ResetPasswordDto,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<SimpleMessageEntity>(
    {
      url: `/api/v1/auth/reset-password`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: resetPasswordDto,
    },
    options,
  );
};

export const getResetPasswordMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof resetPassword>>,
    TError,
    { data: ResetPasswordDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof resetPassword>>,
  TError,
  { data: ResetPasswordDto },
  TContext
> => {
  const mutationKey = ['resetPassword'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof resetPassword>>,
    { data: ResetPasswordDto }
  > = (props) => {
    const { data } = props ?? {};

    return resetPassword(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ResetPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof resetPassword>>
>;
export type ResetPasswordMutationBody = ResetPasswordDto;
export type ResetPasswordMutationError = unknown;

export const useResetPassword = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof resetPassword>>,
    TError,
    { data: ResetPasswordDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof resetPassword>>,
  TError,
  { data: ResetPasswordDto },
  TContext
> => {
  const mutationOptions = getResetPasswordMutationOptions(options);

  return useMutation(mutationOptions);
};

export const resendConfirmEmail = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<SimpleMessageEntity>(
    { url: `/api/v1/auth/resend-confirm-email`, method: 'GET', signal },
    options,
  );
};

export const getResendConfirmEmailQueryKey = () => {
  return [`/api/v1/auth/resend-confirm-email`] as const;
};

export const getResendConfirmEmailQueryOptions = <
  TData = Awaited<ReturnType<typeof resendConfirmEmail>>,
  TError = ResponseErrorEntity,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof resendConfirmEmail>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getResendConfirmEmailQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof resendConfirmEmail>>
  > = ({ signal }) => resendConfirmEmail(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof resendConfirmEmail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ResendConfirmEmailQueryResult = NonNullable<
  Awaited<ReturnType<typeof resendConfirmEmail>>
>;
export type ResendConfirmEmailQueryError = ResponseErrorEntity;

export function useResendConfirmEmail<
  TData = Awaited<ReturnType<typeof resendConfirmEmail>>,
  TError = ResponseErrorEntity,
>(options: {
  query: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof resendConfirmEmail>>,
      TError,
      TData
    >
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof resendConfirmEmail>>,
        TError,
        Awaited<ReturnType<typeof resendConfirmEmail>>
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof customInstance>;
}): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useResendConfirmEmail<
  TData = Awaited<ReturnType<typeof resendConfirmEmail>>,
  TError = ResponseErrorEntity,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof resendConfirmEmail>>,
      TError,
      TData
    >
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof resendConfirmEmail>>,
        TError,
        Awaited<ReturnType<typeof resendConfirmEmail>>
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useResendConfirmEmail<
  TData = Awaited<ReturnType<typeof resendConfirmEmail>>,
  TError = ResponseErrorEntity,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof resendConfirmEmail>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useResendConfirmEmail<
  TData = Awaited<ReturnType<typeof resendConfirmEmail>>,
  TError = ResponseErrorEntity,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof resendConfirmEmail>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getResendConfirmEmailQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const verifyPasswordResetToken = (
  token: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<SimpleMessageEntity>(
    {
      url: `/api/v1/auth/verify-password-reset/${token}`,
      method: 'GET',
      signal,
    },
    options,
  );
};

export const getVerifyPasswordResetTokenQueryKey = (token: string) => {
  return [`/api/v1/auth/verify-password-reset/${token}`] as const;
};

export const getVerifyPasswordResetTokenQueryOptions = <
  TData = Awaited<ReturnType<typeof verifyPasswordResetToken>>,
  TError = unknown,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof verifyPasswordResetToken>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getVerifyPasswordResetTokenQueryKey(token);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof verifyPasswordResetToken>>
  > = ({ signal }) => verifyPasswordResetToken(token, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!token,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof verifyPasswordResetToken>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type VerifyPasswordResetTokenQueryResult = NonNullable<
  Awaited<ReturnType<typeof verifyPasswordResetToken>>
>;
export type VerifyPasswordResetTokenQueryError = unknown;

export function useVerifyPasswordResetToken<
  TData = Awaited<ReturnType<typeof verifyPasswordResetToken>>,
  TError = unknown,
>(
  token: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof verifyPasswordResetToken>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof verifyPasswordResetToken>>,
          TError,
          Awaited<ReturnType<typeof verifyPasswordResetToken>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useVerifyPasswordResetToken<
  TData = Awaited<ReturnType<typeof verifyPasswordResetToken>>,
  TError = unknown,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof verifyPasswordResetToken>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof verifyPasswordResetToken>>,
          TError,
          Awaited<ReturnType<typeof verifyPasswordResetToken>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useVerifyPasswordResetToken<
  TData = Awaited<ReturnType<typeof verifyPasswordResetToken>>,
  TError = unknown,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof verifyPasswordResetToken>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useVerifyPasswordResetToken<
  TData = Awaited<ReturnType<typeof verifyPasswordResetToken>>,
  TError = unknown,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof verifyPasswordResetToken>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getVerifyPasswordResetTokenQueryOptions(token, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getProductCategories = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProductCategoryEntity[]>(
    { url: `/api/v1/products/categories`, method: 'GET', signal },
    options,
  );
};

export const getGetProductCategoriesQueryKey = () => {
  return [`/api/v1/products/categories`] as const;
};

export const getGetProductCategoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getProductCategories>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getProductCategories>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProductCategoriesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProductCategories>>
  > = ({ signal }) => getProductCategories(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProductCategories>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProductCategoriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProductCategories>>
>;
export type GetProductCategoriesQueryError = unknown;

export function useGetProductCategories<
  TData = Awaited<ReturnType<typeof getProductCategories>>,
  TError = unknown,
>(options: {
  query: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getProductCategories>>,
      TError,
      TData
    >
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getProductCategories>>,
        TError,
        Awaited<ReturnType<typeof getProductCategories>>
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof customInstance>;
}): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProductCategories<
  TData = Awaited<ReturnType<typeof getProductCategories>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getProductCategories>>,
      TError,
      TData
    >
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getProductCategories>>,
        TError,
        Awaited<ReturnType<typeof getProductCategories>>
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProductCategories<
  TData = Awaited<ReturnType<typeof getProductCategories>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getProductCategories>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetProductCategories<
  TData = Awaited<ReturnType<typeof getProductCategories>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getProductCategories>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProductCategoriesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getBestSellingProducts = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProductEntity[]>(
    { url: `/api/v1/products/best-selling`, method: 'GET', signal },
    options,
  );
};

export const getGetBestSellingProductsQueryKey = () => {
  return [`/api/v1/products/best-selling`] as const;
};

export const getGetBestSellingProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof getBestSellingProducts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getBestSellingProducts>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetBestSellingProductsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getBestSellingProducts>>
  > = ({ signal }) => getBestSellingProducts(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getBestSellingProducts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBestSellingProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBestSellingProducts>>
>;
export type GetBestSellingProductsQueryError = unknown;

export function useGetBestSellingProducts<
  TData = Awaited<ReturnType<typeof getBestSellingProducts>>,
  TError = unknown,
>(options: {
  query: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getBestSellingProducts>>,
      TError,
      TData
    >
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getBestSellingProducts>>,
        TError,
        Awaited<ReturnType<typeof getBestSellingProducts>>
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof customInstance>;
}): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBestSellingProducts<
  TData = Awaited<ReturnType<typeof getBestSellingProducts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getBestSellingProducts>>,
      TError,
      TData
    >
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getBestSellingProducts>>,
        TError,
        Awaited<ReturnType<typeof getBestSellingProducts>>
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBestSellingProducts<
  TData = Awaited<ReturnType<typeof getBestSellingProducts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getBestSellingProducts>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetBestSellingProducts<
  TData = Awaited<ReturnType<typeof getBestSellingProducts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getBestSellingProducts>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetBestSellingProductsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getMomsAffiliateMarketProducts = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProductEntity[]>(
    { url: `/api/v1/products/moms-affiliate-market`, method: 'GET', signal },
    options,
  );
};

export const getGetMomsAffiliateMarketProductsQueryKey = () => {
  return [`/api/v1/products/moms-affiliate-market`] as const;
};

export const getGetMomsAffiliateMarketProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMomsAffiliateMarketProducts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getMomsAffiliateMarketProducts>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMomsAffiliateMarketProductsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMomsAffiliateMarketProducts>>
  > = ({ signal }) => getMomsAffiliateMarketProducts(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMomsAffiliateMarketProducts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMomsAffiliateMarketProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMomsAffiliateMarketProducts>>
>;
export type GetMomsAffiliateMarketProductsQueryError = unknown;

export function useGetMomsAffiliateMarketProducts<
  TData = Awaited<ReturnType<typeof getMomsAffiliateMarketProducts>>,
  TError = unknown,
>(options: {
  query: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getMomsAffiliateMarketProducts>>,
      TError,
      TData
    >
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getMomsAffiliateMarketProducts>>,
        TError,
        Awaited<ReturnType<typeof getMomsAffiliateMarketProducts>>
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof customInstance>;
}): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMomsAffiliateMarketProducts<
  TData = Awaited<ReturnType<typeof getMomsAffiliateMarketProducts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getMomsAffiliateMarketProducts>>,
      TError,
      TData
    >
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getMomsAffiliateMarketProducts>>,
        TError,
        Awaited<ReturnType<typeof getMomsAffiliateMarketProducts>>
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMomsAffiliateMarketProducts<
  TData = Awaited<ReturnType<typeof getMomsAffiliateMarketProducts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getMomsAffiliateMarketProducts>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetMomsAffiliateMarketProducts<
  TData = Awaited<ReturnType<typeof getMomsAffiliateMarketProducts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getMomsAffiliateMarketProducts>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMomsAffiliateMarketProductsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getBloomersStoreProducts = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProductEntity[]>(
    { url: `/api/v1/products/bloomers-store`, method: 'GET', signal },
    options,
  );
};

export const getGetBloomersStoreProductsQueryKey = () => {
  return [`/api/v1/products/bloomers-store`] as const;
};

export const getGetBloomersStoreProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof getBloomersStoreProducts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getBloomersStoreProducts>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetBloomersStoreProductsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getBloomersStoreProducts>>
  > = ({ signal }) => getBloomersStoreProducts(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getBloomersStoreProducts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBloomersStoreProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBloomersStoreProducts>>
>;
export type GetBloomersStoreProductsQueryError = unknown;

export function useGetBloomersStoreProducts<
  TData = Awaited<ReturnType<typeof getBloomersStoreProducts>>,
  TError = unknown,
>(options: {
  query: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getBloomersStoreProducts>>,
      TError,
      TData
    >
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getBloomersStoreProducts>>,
        TError,
        Awaited<ReturnType<typeof getBloomersStoreProducts>>
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof customInstance>;
}): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBloomersStoreProducts<
  TData = Awaited<ReturnType<typeof getBloomersStoreProducts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getBloomersStoreProducts>>,
      TError,
      TData
    >
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getBloomersStoreProducts>>,
        TError,
        Awaited<ReturnType<typeof getBloomersStoreProducts>>
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBloomersStoreProducts<
  TData = Awaited<ReturnType<typeof getBloomersStoreProducts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getBloomersStoreProducts>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetBloomersStoreProducts<
  TData = Awaited<ReturnType<typeof getBloomersStoreProducts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getBloomersStoreProducts>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetBloomersStoreProductsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getDiscountedProducts = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProductEntity[]>(
    { url: `/api/v1/products/discounted`, method: 'GET', signal },
    options,
  );
};

export const getGetDiscountedProductsQueryKey = () => {
  return [`/api/v1/products/discounted`] as const;
};

export const getGetDiscountedProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof getDiscountedProducts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getDiscountedProducts>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDiscountedProductsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDiscountedProducts>>
  > = ({ signal }) => getDiscountedProducts(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDiscountedProducts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDiscountedProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDiscountedProducts>>
>;
export type GetDiscountedProductsQueryError = unknown;

export function useGetDiscountedProducts<
  TData = Awaited<ReturnType<typeof getDiscountedProducts>>,
  TError = unknown,
>(options: {
  query: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getDiscountedProducts>>,
      TError,
      TData
    >
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getDiscountedProducts>>,
        TError,
        Awaited<ReturnType<typeof getDiscountedProducts>>
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof customInstance>;
}): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDiscountedProducts<
  TData = Awaited<ReturnType<typeof getDiscountedProducts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getDiscountedProducts>>,
      TError,
      TData
    >
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getDiscountedProducts>>,
        TError,
        Awaited<ReturnType<typeof getDiscountedProducts>>
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDiscountedProducts<
  TData = Awaited<ReturnType<typeof getDiscountedProducts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getDiscountedProducts>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetDiscountedProducts<
  TData = Awaited<ReturnType<typeof getDiscountedProducts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getDiscountedProducts>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDiscountedProductsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const logActivity = (
  createActivityLogDto: CreateActivityLogDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    {
      url: `/api/activitylogs`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createActivityLogDto,
      signal,
    },
    options,
  );
};

export const getLogActivityMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logActivity>>,
    TError,
    { data: CreateActivityLogDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof logActivity>>,
  TError,
  { data: CreateActivityLogDto },
  TContext
> => {
  const mutationKey = ['logActivity'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof logActivity>>,
    { data: CreateActivityLogDto }
  > = (props) => {
    const { data } = props ?? {};

    return logActivity(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LogActivityMutationResult = NonNullable<
  Awaited<ReturnType<typeof logActivity>>
>;
export type LogActivityMutationBody = CreateActivityLogDto;
export type LogActivityMutationError = unknown;

export const useLogActivity = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logActivity>>,
    TError,
    { data: CreateActivityLogDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof logActivity>>,
  TError,
  { data: CreateActivityLogDto },
  TContext
> => {
  const mutationOptions = getLogActivityMutationOptions(options);

  return useMutation(mutationOptions);
};
